set -e
tcc=${tcc:=tcc}
> config.h
echo 'int putenv(char *string) { return 0; }' > putenv_stub.c
"$tcc" "-c" "-g"       "-DNO_FLOAT" "getopt.c"
"$tcc" "-c" "-g"       "-DNO_FLOAT" "getopt1.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DHAVE_FCNTL_H" "arscan.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DFILE_TIMESTAMP_HI_RES=0" "commands.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DFILE_TIMESTAMP_HI_RES=0" "file.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DSCCS_GET=\"/nullop\"" "default.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "expand.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-Dvfork=fork" "function.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "implicit.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DHAVE_DUP2" "-DHAVE_STRCHR" "-Dvfork=fork" "job.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DLOCALEDIR=\"/fake-locale\"" "-DPACKAGE=\"fake-make\"" "-DHAVE_MKTEMP" "-DHAVE_GETCWD" "main.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DHAVE_STRERROR" "-DHAVE_VPRINTF" "-DHAVE_ANSI_COMPILER" "-DHAVE_STDARG_H" "misc.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DFILE_TIMESTAMP_HI_RES=0" "-DHAVE_FCNTL_H" "-DLIBDIR=\"${PREFIX}/lib\"" "remake.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "rule.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "signame.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "strcache.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "variable.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "vpath.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "hash.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "remote-stub.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-Iglob" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DHAVE_STDINT_H" "ar.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-Iglob" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DHAVE_DIRENT_H" "dir.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-Iglob" "-DHAVE_INTTYPES_H" "-DHAVE_SA_RESTART" "-DINCLUDEDIR=\"${PREFIX}/include\"" "read.c"
"$tcc" "-c" "-g" "-I." "-DNO_FLOAT" "-DVERSION=\"3.82\"" "version.c"
"$tcc" "-c" "-g"       "-DNO_FLOAT" "-DHAVE_FCNTL_H" "getloadavg.c"
"$tcc" "-c" "-g"       "-DNO_FLOAT" "-Iglob" "-DSTDC_HEADERS" "glob/fnmatch.c"
"$tcc" "-c" "-g"       "-DNO_FLOAT" "-Iglob" "-DHAVE_STRDUP" "-DHAVE_DIRENT_H" "glob/glob.c"
"$tcc" "-c" "-g"       "-DNO_FLOAT" "putenv_stub.c"
"$tcc" "-g" "-static" "-o" "make" "getopt.o" "getopt1.o" "ar.o" "arscan.o" "commands.o" "default.o" "dir.o" "expand.o" "file.o" "function.o" "implicit.o" "job.o" "main.o" "misc.o" "read.o" "remake.o" "rule.o" "signame.o" "strcache.o" "variable.o" "version.o" "vpath.o" "hash.o" "remote-stub.o" "getloadavg.o" "fnmatch.o" "glob.o" "putenv_stub.o"
